// Code generated by "stringer -type ElectionState"; DO NOT EDIT.

package catman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElectionStateStart-0]
	_ = x[ElectionStateOffer-1]
	_ = x[ElectionStateDetermine-2]
	_ = x[ElectionStateElected-3]
	_ = x[ElectionStateReady-4]
	_ = x[ElectionStateFailed-5]
	_ = x[ElectionStateStop-6]
}

const _ElectionState_name = "ElectionStateStartElectionStateOfferElectionStateDetermineElectionStateElectedElectionStateReadyElectionStateFailedElectionStateStop"

var _ElectionState_index = [...]uint8{0, 18, 36, 58, 78, 96, 115, 132}

func (i ElectionState) String() string {
	if i < 0 || i >= ElectionState(len(_ElectionState_index)-1) {
		return "ElectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElectionState_name[_ElectionState_index[i]:_ElectionState_index[i+1]]
}
