// Code generated by "stringer -type ElectionEvent"; DO NOT EDIT.

package catman

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ElectionEventStart-0]
	_ = x[ElectionEventOfferStart-1]
	_ = x[ElectionEventOfferComplete-2]
	_ = x[ElectionEventDetermineStart-3]
	_ = x[ElectionEventDetermineComplete-4]
	_ = x[ElectionEventElectedStart-5]
	_ = x[ElectionEventElectedComplete-6]
	_ = x[ElectionEventReadyStart-7]
	_ = x[ElectionEventReadyComplete-8]
	_ = x[ElectionEventFailed-9]
	_ = x[ElectionEventStopStart-10]
	_ = x[ElectionEventStopComplete-11]
}

const _ElectionEvent_name = "ElectionEventStartElectionEventOfferStartElectionEventOfferCompleteElectionEventDetermineStartElectionEventDetermineCompleteElectionEventElectedStartElectionEventElectedCompleteElectionEventReadyStartElectionEventReadyCompleteElectionEventFailedElectionEventStopStartElectionEventStopComplete"

var _ElectionEvent_index = [...]uint16{0, 18, 41, 67, 94, 124, 149, 177, 200, 226, 245, 267, 292}

func (i ElectionEvent) String() string {
	if i < 0 || i >= ElectionEvent(len(_ElectionEvent_index)-1) {
		return "ElectionEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElectionEvent_name[_ElectionEvent_index[i]:_ElectionEvent_index[i+1]]
}
